[project]
name = "cloud-unmanaged"
version = "0.1.0"
description = "Tool to identify cloud resources not managed by IaC"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.71",
    "rich>=15.0.0",
    "sqlalchemy>=2.0.52",
    "typer>=0.27.1",
    "types-boto3-lite[account,cloudformation,kms,resource-explorer-2]>=1.43.71",
]

[project.scripts]
cloud-unmanaged = "cloud_unmanaged.main:app"

[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.12.3,<0.13"]

[dependency-groups]
dev = [
    "coverage>=7.15.4",
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
    "ty>=0.0.71",
    "vulture>=2.16",
    "yamllint>=1.38.0",
]

[tool.coverage.report]
fail_under = 100
show_missing = true
skip_empty = true

[tool.coverage.run]
branch = true
source = ["src"]

[tool.mypy]
files = ["src", "tests"]
strict = true

[tool.ruff]
line-length = 120

[tool.vulture]
paths = ["src", "tests"]
